/// Flutter icons OotmIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OotmIcons
///      fonts:
///       - asset: fonts/OotmIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OotmIcons {
  OotmIcons._();

  static const _kFontFam = 'OotmIcons';
  static const String? _kFontPkg = null;

  static const IconData back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkEmpty =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkFilled =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favEmpty = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favFilled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe25c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nofilters = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onboarding =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
