// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2PjZwV_P7dqJXq-z2d2wkSRjUCJO0TXA',
    appId: '1:838384085640:web:656208997bd10a0bd1cd3d',
    messagingSenderId: '838384085640',
    projectId: 'odyssey-mobile',
    authDomain: 'odyssey-mobile.firebaseapp.com',
    storageBucket: 'odyssey-mobile.appspot.com',
    measurementId: 'G-FYXT2YKKPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPpZ5COmRKMtKC3m_33lyAjad_eVNF-g',
    appId: '1:838384085640:android:d2a8c48d547e1989d1cd3d',
    messagingSenderId: '838384085640',
    projectId: 'odyssey-mobile',
    storageBucket: 'odyssey-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKvhS4WDjZBKWQwdSeWKwvnNawUwvzjw',
    appId: '1:838384085640:ios:c024b8f5b20636b2d1cd3d',
    messagingSenderId: '838384085640',
    projectId: 'odyssey-mobile',
    storageBucket: 'odyssey-mobile.appspot.com',
    androidClientId: '838384085640-icl3hi7f011j72kmtq38sklege293aep.apps.googleusercontent.com',
    iosClientId: '838384085640-2vs8l95ja45nlpiulv0duc9piun1j11j.apps.googleusercontent.com',
    iosBundleId: 'com.odyssey.lappka',
  );
}
