/// Flutter icons OotmIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OotmIcons
///      fonts:
///       - asset: fonts/OotmIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OotmIcons {
  OotmIcons._();

  static const _kFontFam = 'OotmIcons';
  static const String? _kFontPkg = null;

  static const IconData arrowLeft = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleCheck =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emptyCheck =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favouritesFilled =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourites =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filters = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
