// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:odyssey_mobile/core/data/db/hive/hive_service.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CityDataHiveModelAdapter());
    registerAdapter(CityHiveModelAdapter());
    registerAdapter(InfoGroupHiveModelAdapter());
    registerAdapter(InfoHiveModelAdapter());
    registerAdapter(PerformanceGroupHiveModelAdapter());
    registerAdapter(PerformanceHiveModelAdapter());
    registerAdapter(ProblemHiveModelAdapter());
    registerAdapter(SponsorHiveModelAdapter());
    registerAdapter(StageHiveModelAdapter());
  }
}
