
name: deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: 37.27.71.201
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd OdysejaMobile/OdysejaMobile 
            git pull --ff-only
            rm -rf build/web
            flutter pub get
            flutter build web --no-tree-shake-icons
            echo "$(git rev-parse --short HEAD)" > build/web/.last_build_id
            docker build --pull -t grzybek/odyseja-pwa:latest .
            docker rm -f odyseja-pwa || true
            docker run --name odyseja-pwa --restart unless-stopped --net=host -d grzybek/odyseja-pwa:latest
